CREATE DATABASE IF NOT EXISTS `metalk`;

USE `metalk`;

CREATE TABLE IF NOT EXISTS `users`
(
  id CHAR(36) PRIMARY KEY DEFAULT(UUID()),
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(500) NOT NULL,
  created_at TIMESTAMP DEFAULT(CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS `messages`
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  from_user CHAR(36) NOT NULL,
  to_user CHAR(36) NOT NULL,
  content VARCHAR(500) NOT NULL
  created_at TIMESTAMP DEFAULT(CURRENT_TIMESTAMP),
  FOREIGN KEY (from_user) REFERENCES users(id),
  FOREIGN KEY (to_user) REFERENCES users(id)
);